# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
podLabels:
  livspace.com/event-system: Local
image:
  repository: draft
  tag: dev
  pullPolicy: IfNotPresent
service:
  name: REPLACE_ME_APP_NAME
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    name: http
    protocol: TCP
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
probePort: 8080 #internal port,
probePath: /actuator/health
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10

ingress:
  enabled: false

env:
  enabled: false
  values:
  - name: ENV_NAME
    value: some value

config:
  enabled: false
  mountPath: /etc/REPLACE_ME_APP_NAME
  files:
    config.yml: |-
      profiling:                      No
