APP:
  appName: REPLACE_ME_APP_NAME
  Repo: git@gitlab.com:REPLACE_ME_ORG/REPLACE_ME_GROUP_NAME/REPLACE_ME_APP_NAME.git
  lang: $PACK

Chart:
  chartUrl: git@github.com:livspaceeng/draft-charts.git
  tag: latest
  valuesFile: values.yaml